name: dart_foundation
description: A starting point for Dart libraries or applications.
version: 1.0.0+2
repository: https://github.com/mufsalup/dart_foundation.git

environment:
  sdk: ^3.10.3

# Add regular dependencies here.
dependencies:
  dartz: ^0.10.1
  meta: ^1.17.0
  uuid: ^4.5.3


dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
